# Generated by Django 5.1.4 on 2025-01-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinance',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Логин')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=20, verbose_name='Фамилия')),
                ('total_amount', models.FloatField(default=0, verbose_name='Общая сумма')),
            ],
        ),
    ]
